version: '3.9'

volumes:
  pg_data:

services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    env_file: .test.env
    volumes:
      - pg_data:/var/lib/postgresql/data
    networks:
      - pomodoro-net

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
    networks:
      - pomodoro-net

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - pomodoro-net

  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      - rabbitmq
      - db
      - cache
    networks:
      - pomodoro-net

networks:
  pomodoro-net:
    driver: bridge
