version: '3.9'

volumes:
  pg_data:

services:
  db:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '6432:6432'
    environment:
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_HOST: ${TEST_DB_HOST}
      POSTGRES_PORT: ${TEST_DB_PORT}
    volumes:
      - pg_data:/var/lib/postgresql/test_data

  cache:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
