version: '3.9'

volumes:
  pg_data:

services:
  db-test:
    image: postgres:16.2
    restart: always
    shm_size: 128mb
    ports:
      - '5432:5432'
    env_file: .test.env
    volumes:
      - pg_data:/var/lib/postgresql/test_data

  cache-test:
    image: redis:7.2.4-alpine
    restart: always
    ports:
      - '6379:6379'
