"""alter_user_profiles_all_fields_is_optional

Revision ID: 3e740c7f52bb
Revises: ca13fc205578
Create Date: 2025-01-19 03:04:57.388503

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e740c7f52bb'
down_revision: Union[str, None] = 'ca13fc205578'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('user_profiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profiles', 'password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('user_profiles', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
