"""user_init

Revision ID: 5b06ec6b02e2
Revises: b3a5cd1b73c7
Create Date: 2025-02-20 18:36:42.487996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5b06ec6b02e2'
down_revision: Union[str, None] = 'b3a5cd1b73c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
