"""UserProfile.yandex_access_token

Revision ID: 9dfa8517c866
Revises: 12fbfa793c8c
Create Date: 2025-02-17 15:21:42.413095

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9dfa8517c866'
down_revision: Union[str, None] = '12fbfa793c8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('yandex_access_token', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'yandex_access_token')
    # ### end Alembic commands ###
