"""extend_user_model

Revision ID: ca13fc205578
Revises: f5d5ec4f1a4e
Create Date: 2025-01-19 01:51:25.384755

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ca13fc205578'
down_revision: Union[str, None] = 'f5d5ec4f1a4e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_profiles', sa.Column('google_access_token', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('email', sa.String(), nullable=True))
    op.add_column('user_profiles', sa.Column('name', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_profiles', 'name')
    op.drop_column('user_profiles', 'email')
    op.drop_column('user_profiles', 'google_access_token')
    # ### end Alembic commands ###
